version: '2'
services:
    store-app:
        image: store
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://store-mysql:3306/store?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=store-elasticsearch:9300
        ports:
            - 8080:8080
    store-mysql:
        extends:
            file: mysql.yml
            service: store-mysql
    store-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: store-elasticsearch
